In [32]:
%config IPCompleter.greedy = False

### <span style="font-family: 'D2Coding'">1.5.1 넘파이 가져오기</span>

In [1]:
import numpy as np

### <span style="font-family: 'D2Coding'">1.5.2 넘파이 배열 생성하기</span>

In [2]:
x = np.array([1.0, 2.0, 3.0])

In [3]:
print(x)

[1. 2. 3.]


In [4]:
type(x)

numpy.ndarray

### <span style="font-family: 'D2Coding'">1.5.3 넘파이의 산술 연산</span>

In [5]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

In [6]:
x + y

array([3., 6., 9.])

In [7]:
x - y

array([-1., -2., -3.])

In [8]:
x * y

array([ 2.,  8., 18.])

In [9]:
x / y

array([0.5, 0.5, 0.5])

In [10]:
x / 2.0

array([0.5, 1. , 1.5])

### <span style="font-family: 'D2Coding'">1.5.4 넘파이의 N차원 배열</span>

In [14]:
A = np.array([[1,2,],[3,4,]])

In [15]:
print(A)

[[1 2]
 [3 4]]


In [16]:
A.shape

(2, 2)

In [17]:
A.dtype

dtype('int32')

In [18]:
B = np.array([[3,0,],[0,6,]])

In [19]:
A + B

array([[ 4,  2],
       [ 3, 10]])

In [20]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [21]:
print(A)

[[1 2]
 [3 4]]


In [22]:
A * 10

array([[10, 20],
       [30, 40]])

### <span style="font-family: 'D2Coding'">1.5.5 브로드캐스트</span>

In [23]:
A = np.array([[1,2],[3,4]])
B = np.array([10,20])

In [24]:
A

array([[1, 2],
       [3, 4]])

In [25]:
B

array([10, 20])

In [26]:
A * B

array([[10, 40],
       [30, 80]])

In [27]:
B * A

array([[10, 40],
       [30, 80]])

### <span style="font-family: 'D2Coding'">1.5.6 원소 접근</span>

In [28]:
X = np.array([[51, 55], [14, 19], [0, 4]])

In [29]:
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [30]:
X[0]    # 0행

array([51, 55])

In [33]:
X[0][1]    # (0, 1) 위치의 원소

55

In [34]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [35]:
X = X.flatten()    # X를 1차원 배열로 변환 (평탄화)

In [37]:
print(X)    # 인덱스가 0, 2, 4,인 원소 얻기

[51 55 14 19  0  4]


In [38]:
X > 15

array([ True,  True, False,  True, False, False])

In [39]:
X[X > 15]

array([51, 55, 19])